import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import BrandExample from "../components/navbar";
import { useUser } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user } = useUser();
  return (
    <>
      <Head>
        <title>Sample Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BrandExample></BrandExample>
      <main className={styles.main}>
        <h1>Home Page</h1>

        {!user && <h1>You are currently not logged in</h1>}
        {user && <h1>Hello {user.name}</h1>}
      </main>
    </>
  );
}
