import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import BrandExample from "../components/navbar";
import { useUser } from "@auth0/nextjs-auth0/client";
import Nav from "react-bootstrap/Nav";
import Script from "next/script";
import { useConsent } from "@/lib/useConsent";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { user } = useUser();
  const [consent, handleConsent] = useConsent();
  console.log(user);
  return (
    <>
      <Head>
        <title>Sample Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {consent && (
          <Script
            async
            src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"
          />
        )}
      </Head>

      <header className="bg-primary text-white">
        <main>
          <div className="container my-5">
            <div className="row p-4 pb-0 pe-lg-0 pt-lg-0 align-items-center rounded-3 border shadow-lg ">
              <div className="col-lg-7 p-3 p-lg-3 pt-lg-1">
                <h1 className="display-6 fw-bold lh-1">
                  Revolutionize your teaching
                </h1>
                <p className="lead">
                  Empower your students with cutting-edge software engineering
                  skills. Join MyWebClass and discover advanced technologies
                  that will transform your teaching and their learning journey.
                </p>
                <div className="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                  <button
                    type="button"
                    className="btn btn-success btn-lg px-4 me-md-2 fw-bold"
                  >
                    Start Here
                  </button>
                </div>
              </div>
              <div className="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
                <img
                  className="rounded-lg-3 img-fluid"
                  src="https://raw.githubusercontent.com/NJIT-WIS/mywebclass-simulation-advanced/master/src/assets/images/teacher.gif"
                  alt="a teacher with students"
                  width="720"
                />
              </div>
            </div>
          </div>
        </main>
      </header>
      <section className="py-5" id="aboutus">
        <div className="container">
          <h2 className="mb-4">About Us</h2>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at
            lacus in mauris iaculis consectetur vel a neque. Praesent venenatis
            nisi quis eros mollis consequat. Curabitur euismod viverra
            consectetur. Ut nec risus orci. Aenean euismod odio nisl, non varius
            quam lacinia vel.
          </p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at
            lacus in mauris iaculis consectetur vel a neque. Praesent venenatis
            nisi quis eros mollis consequat. Curabitur euismod viverra
            consectetur. Ut nec risus orci. Aenean euismod odio nisl, non varius
            quam lacinia vel. Integer suscipit sapien quis risus elementum
            imperdiet.
          </p>
        </div>
        <div className="container" id="services">
          <h2 className="mb-4">Our Services</h2>
          <div className="row">
            <div className="col-md-4">
              <div className="card">
                <div className="card-body">
                  <h4 className="card-title">Service 1</h4>
                  <p className="card-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                    at lacus in mauris iaculis consectetur vel a neque. Praesent
                    venenatis nisi quis eros mollis consequat.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-md-4">
              <div className="card">
                <div className="card-body">
                  <h4 className="card-title">Service 2</h4>
                  <p className="card-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                    at lacus in mauris iaculis consectetur vel a neque. Praesent
                    venenatis nisi quis eros mollis consequat.
                  </p>
                </div>
              </div>
            </div>
            <div className="col-md-4">
              <div className="card">
                <div className="card-body">
                  <h4 className="card-title">Service 3</h4>
                  <p className="card-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                    at lacus in mauris iaculis consectetur vel a neque. Praesent
                    venenatis nisi quis eros mollis consequat.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
